# Generated by Django 4.0.4 on 2022-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('date_in', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='номер телефона')),
                ('elmail', models.EmailField(max_length=254, unique=True, verbose_name='элетронная почта')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('is_sended', models.BooleanField(verbose_name='отправлено')),
                ('expire', models.DateField(verbose_name='дата истечения')),
                ('vvcard', models.IntegerField(default='НЕТ КАРТЫ', verbose_name='номер карты ВВ')),
            ],
        ),
    ]
