# Generated by Django 4.0.4 on 2022-05-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='дата посещения')),
                ('gid', models.IntegerField(null=True, verbose_name='идентификатор')),
                ('expire', models.CharField(max_length=64, null=True, verbose_name='дата истечения на момент акции')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('vvcard', models.CharField(default='НЕТ КАРТЫ', max_length=64, verbose_name='номер карты ВВ на момент акции')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64, unique=True, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(null=True, unique=True, verbose_name='идентификатор')),
                ('date_in', models.DateField(verbose_name='дата добавления')),
                ('is_sended', models.BooleanField(null=True, verbose_name='отправлено')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('expire', models.CharField(max_length=64, null=True, verbose_name='дата истечения')),
                ('vvcard', models.CharField(default='НЕТ КАРТЫ', max_length=64, verbose_name='номер карты ВВ')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(null=True, unique=True, verbose_name='идентификатор')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('phone', models.CharField(default=' - ', max_length=64, verbose_name='номер телефона')),
                ('elmail', models.EmailField(max_length=254, verbose_name='элетронная почта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.users')),
            ],
        ),
    ]
