# Generated by Django 4.0.4 on 2022-06-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('chp_point', models.BooleanField(default=True, verbose_name='принадлежность пункта сбора "Чистому Петербургу"')),
                ('accrual_restrict', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')], default=1, verbose_name='ограничение сколько раз в неделю можно начислять от 1-7')),
                ('cost_by_visit', models.IntegerField(default=0, verbose_name='стоимость посещения не участником')),
                ('accrual_restrict', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven')], default=1, verbose_name='ограничение для не участников клуба 1-7')),
                ('cost_by_nonmember', models.IntegerField(default=0, verbose_name='стоимость посещения')),
            ],
        ),
    ]
