# Generated by Django 4.0.4 on 2022-05-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentReportsVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата отправки')),
                ('memb_count', models.IntegerField(null=True, verbose_name='количество разных участников')),
                ('bonus_count', models.IntegerField(null=True, verbose_name='количество начислений')),
                ('bonus_rate', models.IntegerField(null=True, verbose_name='количество бонусов за посещение')),
                ('report_type', models.CharField(default='event', max_length=64, verbose_name='тип отчёта event|subscrip')),
            ],
        ),
    ]
