# Generated by Django 4.0.4 on 2022-04-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_sended',
        ),
        migrations.RemoveField(
            model_name='users',
            name='vvcard',
        ),
        migrations.AddField(
            model_name='users',
            name='gid',
            field=models.CharField(default=None, max_length=64, unique=True, verbose_name='идентификатор'),
        ),
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sended', models.BooleanField(verbose_name='отправлено')),
                ('expire', models.DateField(verbose_name='дата истечения')),
                ('vvcard', models.IntegerField(default='НЕТ КАРТЫ', verbose_name='номер карты ВВ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.users')),
            ],
        ),
    ]
