# Generated by Django 4.0.4 on 2022-05-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='elmail',
            field=models.EmailField(max_length=254, verbose_name='элетронная почта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.BigIntegerField(default=' - ', verbose_name='номер телефона'),
        ),
    ]
