# Generated by Django 4.0.4 on 2022-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_contacts_elmail_alter_contacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default=' - ', max_length=64, verbose_name='номер телефона'),
        ),
    ]
