# Generated by Django 4.0.4 on 2022-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_roles_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='gid',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='идентификатор'),
        ),
    ]
