# Generated by Django 4.0.4 on 2022-05-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_contacts_gid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='gid',
            new_name='contact_gid',
        ),
    ]
