# Generated by Django 4.0.4 on 2022-05-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_rename_gid_contacts_contact_gid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_gid',
            new_name='gid',
        ),
    ]
