# Generated by Django 4.0.4 on 2022-05-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_rename_contact_gid_contacts_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='gid',
            field=models.IntegerField(null=True, unique=True, verbose_name='идентификатор'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gid',
            field=models.IntegerField(null=True, unique=True, verbose_name='идентификатор'),
        ),
    ]
